/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicauca.restaurantehexagonal.presentacion.app;

import co.edu.unicauca.restaurantehexagonal.access.Factory;
import co.edu.unicauca.restaurantehexagonal.dominio.entities.Restaurante;
import co.edu.unicauca.restaurantehexagonal.dominio.interfaces.IRestauranteRepository;
import co.edu.unicauca.restaurantehexagonal.dominio.services.RestauranteService;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDWIN ADRADA
 */
public class GUIRestaurante extends javax.swing.JFrame {

    int user = 0;
    String restId = "";
    /**
     * Creates new form GUIRestaurante
     */
    public GUIRestaurante() {
        initComponents();
        tblRestaurantes.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)tblRestaurantes.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        tblRestaurantes.setGridColor(Color.WHITE);
        tblRestaurantes.setForeground(Color.WHITE);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        tblRestaurantes.setOpaque(false);
        ((DefaultTableCellRenderer)tblRestaurantes.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        this.setSize(720, 480);
        this.setLocationRelativeTo(null);
        llenarTabla();
    }
    
    public GUIRestaurante(int num) {
        initComponents();
        tblRestaurantes.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)tblRestaurantes.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        tblRestaurantes.setGridColor(Color.WHITE);
        tblRestaurantes.setForeground(Color.WHITE);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        tblRestaurantes.setOpaque(false);
        ((DefaultTableCellRenderer)tblRestaurantes.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        user = num;
        if(user == 1){
            btnSalir.setVisible(false);
            btnCerrarSesion.setVisible(true);
        }
        else{
            btnCerrarSesion.setVisible(false);
            btnSalir.setVisible(true);
        }
        this.setSize(720, 480);
        this.setLocationRelativeTo(null);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestaurantes = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantes = new javax.swing.JTable();
        btnContacto = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestaurantes.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblRestaurantes.setForeground(new java.awt.Color(255, 51, 43));
        lblRestaurantes.setText("Restaurantes");
        getContentPane().add(lblRestaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 295, 72));

        btnSalir.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 100, 50));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 51, 43));
        btnCerrarSesion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 100, 50));

        btnSelect.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(255, 51, 43));
        btnSelect.setText("Selecionar restaurante");
        btnSelect.setBorder(null);
        btnSelect.setBorderPainted(false);
        btnSelect.setContentAreaFilled(false);
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        tblRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Eslogan", "Direccion", "Telefono", "Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRestaurantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRestaurantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRestaurantes);
        if (tblRestaurantes.getColumnModel().getColumnCount() > 0) {
            tblRestaurantes.getColumnModel().getColumn(1).setResizable(false);
            tblRestaurantes.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 550, 210));

        btnContacto.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnContacto.setForeground(new java.awt.Color(255, 255, 255));
        btnContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cc.png"))); // NOI18N
        btnContacto.setText("Contactanos");
        btnContacto.setBorder(null);
        btnContacto.setBorderPainted(false);
        btnContacto.setContentAreaFilled(false);
        btnContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactoActionPerformed(evt);
            }
        });
        getContentPane().add(btnContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo restaurante esquina.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 72, 60));
        lblLogo.getAccessibleContext().setAccessibleParent(this);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Base2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed

        if(restId.equals("")){
           JOptionPane.showMessageDialog(null, "No has seleccionado ningun restaurante", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(user == 1){
            Usuario user = new Usuario(restId);
            user.setVisible(true);
            this.dispose();
        }
        else{
            Visitante vist = new Visitante(restId);
            vist.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        //resp =0 si, resp = 1 no.
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar sesion?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp==0){
        IniciarSesion login = new IniciarSesion();
        login.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactoActionPerformed
        Contacto cont = new Contacto(8);
        cont.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContactoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //resp =0 si, resp = 1 no.
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp==0){
        IniciarSesion login = new IniciarSesion();
        login.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblRestaurantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRestaurantesMouseClicked
        DefaultTableModel tabla1 = (DefaultTableModel) tblRestaurantes.getModel();
        restId = String.valueOf(tabla1.getValueAt(tblRestaurantes.getSelectedRow(),0));
    }//GEN-LAST:event_tblRestaurantesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRestaurante().setVisible(true);
            }
        });
    }
    
    private void llenarTabla() {
        IRestauranteRepository service = Factory.getInstance().getRepositoryRestaurante();
        RestauranteService restauranteService = new RestauranteService(service);
        
        List<Restaurante> objListRestaurantes = new ArrayList<Restaurante>();
        objListRestaurantes = restauranteService.listRestaurantes();
        
        String matriz[][] = new String[objListRestaurantes.size()][6];
        for (int i = 0; i < objListRestaurantes.size(); i++) {
            matriz[i][0] = objListRestaurantes.get(i).getNit();
            matriz[i][1] = objListRestaurantes.get(i).getNombreRestaurante();
            matriz[i][2] = objListRestaurantes.get(i).getEslogan();
            matriz[i][3] = objListRestaurantes.get(i).getDireccion();
            matriz[i][4] = objListRestaurantes.get(i).getTelefono();
            matriz[i][5] = objListRestaurantes.get(i).getCiudad();
        }
        
        tblRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ID", "Nombre", "Eslogan", "Direccion", "Telefono", "Ciudad"
                }
        ));
        
        //Ancho de columnas
        tblRestaurantes.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblRestaurantes.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblRestaurantes.getColumnModel().getColumn(3).setPreferredWidth(90);
        tblRestaurantes.getColumnModel().getColumn(5).setPreferredWidth(50);
        
        //Altura de filas
        tblRestaurantes.setRowHeight(30);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnContacto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRestaurantes;
    private javax.swing.JTable tblRestaurantes;
    // End of variables declaration//GEN-END:variables


}
