/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicauca.restaurantehexagonal.presentacion.app;

import co.edu.unicauca.restaurantehexagonal.access.Factory;
import co.edu.unicauca.restaurantehexagonal.dominio.interfaces.IUsuarioRepository;
import co.edu.unicauca.restaurantehexagonal.dominio.services.UsuarioService;
import co.edu.unicauca.restaurantehexagonal.dominio.entities.Usuario;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Registro de Usuarios");
        
    }
    private String SeleccionGenero(){
        String genero = txtGenero.getSelectedItem().toString();
        if(genero == "Masculino"){
            genero = "M";
        }
        if (genero == "Femenino"){
            genero = "F";
        }
        return genero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNomUsuario = new javax.swing.JTextField();
        txtGenero = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        imgWp9 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        imgInstagram = new javax.swing.JLabel();
        imgFb = new javax.swing.JLabel();
        imgWp10 = new javax.swing.JLabel();
        imgWp11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 480));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setText("REGISTRO DE USUARIO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 40, 220, 26);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("Nombre de Usuario:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 160, 131, 17);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setText("Nombre(s):");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 80, 73, 17);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("Apellido(s):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 120, 74, 17);

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setText("Genero:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 240, 53, 17);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Celular:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 320, 44, 17);

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 280, 41, 17);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(480, 200, 200, 30);

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 200, 80, 17);
        jPanel1.add(txtNombres);
        txtNombres.setBounds(480, 80, 200, 30);
        jPanel1.add(txtApellidos);
        txtApellidos.setBounds(480, 120, 200, 30);
        jPanel1.add(txtNomUsuario);
        txtNomUsuario.setBounds(510, 160, 170, 30);

        txtGenero.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        txtGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        jPanel1.add(txtGenero);
        txtGenero.setBounds(480, 240, 120, 30);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(480, 280, 200, 30);

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumero);
        txtNumero.setBounds(480, 320, 200, 30);

        btnRegistro.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        btnRegistro.setText("REGISTRARSE");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro);
        btnRegistro.setBounds(460, 410, 150, 40);

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel10.setText("Cedula:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 360, 50, 17);

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtID);
        txtID.setBounds(480, 360, 200, 30);

        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 20, 90, 30);

        imgWp9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel1.add(imgWp9);
        imgWp9.setBounds(560, 0, 130, 480);

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_restaurante .png"))); // NOI18N
        jPanel1.add(imgLogo);
        imgLogo.setBounds(60, 130, 199, 159);

        imgInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/instagram_icon_125245.png"))); // NOI18N
        jPanel1.add(imgInstagram);
        imgInstagram.setBounds(100, 320, 32, 32);

        imgFb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fb_icon-icons.com_65434.png"))); // NOI18N
        jPanel1.add(imgFb);
        imgFb.setBounds(170, 320, 32, 32);

        imgWp10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel1.add(imgWp10);
        imgWp10.setBounds(330, 0, 151, 480);

        imgWp11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel1.add(imgWp11);
        imgWp11.setBounds(410, -10, 151, 490);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        IUsuarioRepository repo = Factory.getInstance().getRepositoryUsuario();
        UsuarioService customerService = new UsuarioService(repo);

        
        try {
            if (txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtEmail.getText().isEmpty()
                    || txtNumero.getText().isEmpty() || jPasswordField1.getText().isEmpty() || txtNomUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese datos", "Campos vacios", JOptionPane.ERROR_MESSAGE);
            } else {
                
                Usuario usuario = new Usuario();
                usuario.setUserNombre(txtNombres.getText());
                usuario.setUserApellido(txtApellidos.getText());
                usuario.setUserPassword(jPasswordField1.getText());
                usuario.setUserName(txtNomUsuario.getText());
                usuario.setUserEmail(txtEmail.getText());
                usuario.setUserCelular(txtNumero.getText());
                usuario.setUserGenero(SeleccionGenero()); 
                usuario.setUserId(Integer.parseInt(txtID.getText()));

                String registro = customerService.createUsuario(usuario);
                
                JOptionPane.showMessageDialog(null, registro, "ATENCION", JOptionPane.ERROR_MESSAGE);
                txtNombres.setText("");
                txtApellidos.setText("");
                jPasswordField1.setText("");
                txtNomUsuario.setText("");
                txtEmail.setText("");
                txtNumero.setText("");
                txtID.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo numeros" , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo numeros" , "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_txtIDKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IniciarSesion ins = new IniciarSesion();
        ins.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel imgFb;
    private javax.swing.JLabel imgInstagram;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgWp10;
    private javax.swing.JLabel imgWp11;
    private javax.swing.JLabel imgWp9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtGenero;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNomUsuario;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
